# DataSource
spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  datasource:
    url: jdbc:mysql://39.97.114.3:3306/experiment_management_system?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  main:
    allow-bean-definition-overriding: true
  resources:
    static-locations: file:/always

logging:
  level:
    com.always.ssm_experiment_management_system_server.mapper: debug